###
GET http://localhost:4000/api/all/perro
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDM1NDc4OGVmYzIzMjA3ODBkZDEwMWYiLCJpYXQiOjE2MTU5MTc5MzcsImV4cCI6MTYxNTk2MTEzN30.MXuC5OdXFodIPVgqcZHoHG6OtRylysmDaFtMWt5U7Bk