###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name":"Mauro Gauto Elvis",
    "password": "321654",
    "email": "elvis199@gmail.com"
}

###
GET http://localhost:4000/api/users

###
PUT http://localhost:4000/api/users/60354788efc2320780dd101f
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDM1NDc4OGVmYzIzMjA3ODBkZDEwMWYiLCJpYXQiOjE2MTQxMTEyMTcsImV4cCI6MTYxNDE1NDQxN30.dzmT7dpqQRJ91IjOByNbA5x5KdP18ZXwnD8QR8tegCg

{
    "name":"Mauro",
    "password": "321654",
    "google": "true",
    "email": "elvis19@gmail.com",
    "role": "admin"
}
###
DELETE http://localhost:4000/api/users/6035592d7dc52238f8cf8143
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDM1NDc4OGVmYzIzMjA3ODBkZDEwMWYiLCJpYXQiOjE2MTQxMTEyMTcsImV4cCI6MTYxNDE1NDQxN30.dzmT7dpqQRJ91IjOByNbA5x5KdP18ZXwnD8QR8tegCg


// AUTH API REST

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "elvis19@gmail.com",
    "password": "321654"
}